export const AUTH_LOGIN_REQUEST = "AUTH_LOGIN_REQUEST";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAIL = "AUTH_LOGIN_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const AUTH_REGISTER_REQUEST = "AUTH_REGISTER_REQUEST";
export const AUTH_REGISTER_SUCCESS = "AUTH_REGISTER_SUCCESS";
export const AUTH_REGISTER_FAIL = "AUTH_REGISTER_FAIL";
export const AUTH_REGISTER_RESET = "AUTH_REGISTER_RESET";

export const AUTH_PASSWORD_UPDATE_REQUEST = "AUTH_PASSWORD_UPDATE_REQUEST";
export const AUTH_PASSWORD_UPDATE_SUCCESS = "AUTH_PASSWORD_UPDATE_SUCCESS";
export const AUTH_PASSWORD_UPDATE_FAIL = "AUTH_PASSWORD_UPDATE_FAIL";
export const AUTH_PASSWORD_UPDATE_RESET = "AUTH_PASSWORD_UPDATE_RESET";
