export const BRANCH_CREATE_REQUEST = 'BRANCH_CREATE_REQUEST';
export const BRANCH_CREATE_SUCCESS = 'BRANCH_CREATE_SUCCESS';
export const BRANCH_CREATE_FAIL = 'BRANCH_CREATE_FAIL';
export const BRANCH_CREATE_RESET = 'BRANCH_CREATE_RESET';

export const BRANCH_EDIT_REQUEST = 'BRANCH_EDIT_REQUEST';
export const BRANCH_EDIT_SUCCESS = 'BRANCH_EDIT_SUCCESS';
export const BRANCH_EDIT_FAIL = 'BRANCH_EDIT_FAIL';
export const BRANCH_EDIT_RESET = 'BRANCH_EDIT_RESET';

export const BRANCH_LIST_REQUEST = 'BRANCH_LIST_REQUEST';
export const BRANCH_LIST_SUCCESS = 'BRANCH_LIST_SUCCESS';
export const BRANCH_LIST_FAIL = 'BRANCH_LIST_FAIL';

export const BRANCH_DETAILS_REQUEST = 'BRANCH_DETAILS_REQUEST';
export const BRANCH_DETAILS_SUCCESS = 'BRANCH_DETAILS_SUCCESS';
export const BRANCH_DETAILS_FAIL = 'BRANCH_DETAILS_FAIL';
