export const CONTRIBUTOR_CREATE_REQUEST = 'CONTRIBUTOR_CREATE_REQUEST';
export const CONTRIBUTOR_CREATE_SUCCESS = 'CONTRIBUTOR_CREATE_SUCCESS';
export const CONTRIBUTOR_CREATE_FAIL = 'CONTRIBUTOR_CREATE_FAIL';
export const CONTRIBUTOR_CREATE_RESET = 'CONTRIBUTOR_CREATE_RESET';

export const CONTRIBUTOR_LIST_REQUEST = 'CONTRIBUTOR_LIST_REQUEST';
export const CONTRIBUTOR_LIST_SUCCESS = 'CONTRIBUTOR_LIST_SUCCESS';
export const CONTRIBUTOR_LIST_FAIL = 'CONTRIBUTOR_LIST_FAIL';

export const CONTRIBUTOR_DETAILS_REQUEST = 'CONTRIBUTOR_DETAIL_REQUEST';
export const CONTRIBUTOR_DETAILS_SUCCESS = 'CONTRIBUTOR_DETAIL_SUCCESS';
export const CONTRIBUTOR_DETAILS_FAIL = 'CONTRIBUTOR_DETAIL_FAIL';
export const CONTRIBUTOR_DETAILS_RESET = 'CONTRIBUTOR_DETAILS_RESET';
