export const INVESTMENT_CREATE_REQUEST = 'INVESTMENT_CREATE_REQUEST';
export const INVESTMENT_CREATE_SUCCESS = 'INVESTMENT_CREATE_SUCCESS';
export const INVESTMENT_CREATE_FAIL = 'INVESTMENT_CREATE_FAIL';
export const INVESTMENT_CREATE_RESET = 'INVESTMENT_CREATE_RESET';

export const INVESTMENT_CONFIRM_REQUEST = 'INVESTMENT_CONFIRM_REQUEST';
export const INVESTMENT_CONFIRM_SUCCESS = 'INVESTMENT_CONFIRM_SUCCESS';
export const INVESTMENT_CONFIRM_FAIL = 'INVESTMENT_CONFIRM_FAIL';
export const INVESTMENT_CONFIRM_RESET = 'INVESTMENT_CONFIRM_RESET';

export const INVESTMENT_UPDATE_REQUEST = 'INVESTMENT_UPDATE_REQUEST';
export const INVESTMENT_UPDATE_SUCCESS = 'INVESTMENT_UPDATE_SUCCESS';
export const INVESTMENT_UPDATE_FAIL = 'INVESTMENT_UPDATE_FAIL';
export const INVESTMENT_UPDATE_RESET = 'INVESTMENT_UPDATE_RESET';

export const RECEIPT_CREATE_REQUEST = 'RECEIPT_CREATE_REQUEST';
export const RECEIPT_CREATE_SUCCESS = 'RECEIPT_CREATE_SUCCESS';
export const RECEIPT_CREATE_FAIL = 'RECEIPT_CREATE_FAIL';
export const RECEIPT_CREATE_RESET = 'RECEIPT_CREATE_RESET';

export const MOU_CREATE_REQUEST = 'MOU_CREATE_REQUEST';
export const MOU_CREATE_SUCCESS = 'MOU_CREATE_SUCCESS';
export const MOU_CREATE_FAIL = 'MOU_CREATE_FAIL';
export const MOU_CREATE_RESET = 'MOU_CREATE_RESET';

export const INVESTMENT_LIST_REQUEST = 'INVESTMENT_LIST_REQUEST';
export const INVESTMENT_LIST_SUCCESS = 'INVESTMENT_LIST_SUCCESS';
export const INVESTMENT_LIST_FAIL = 'INVESTMENT_LIST_FAIL';

export const INVESTMENT_DETAILS_REQUEST = 'INVESTMENT_DETAILS_REQUEST';
export const INVESTMENT_DETAILS_SUCCESS = 'INVESTMENT_DETAILS_SUCCESS';
export const INVESTMENT_DETAILS_FAIL = 'INVESTMENT_CREATE_FAIL';
