export const STAFF_LIST_REQUEST = 'STAFF_LIST_REQUEST';
export const STAFF_LIST_SUCCESS = 'STAFF_LIST_SUCCESS';
export const STAFF_LIST_FAIL = 'STAFF_LIST_FAIL';

export const STAFF_DETAILS_REQUEST = 'STAFF_DETAILS_REQUEST';
export const STAFF_DETAILS_SUCCESS = 'STAFF_DETAILS_SUCCESS';
export const STAFF_DETAILS_FAIL = 'STAFF_DETAILS_FAIL';

export const STAFF_REGISTER_REQUEST = 'STAFF_REGISTER_REQUEST';
export const STAFF_REGISTER_SUCCESS = 'STAFF_REGISTER_SUCCESS';
export const STAFF_REGISTER_FAIL = 'STAFF_REGISTER_FAIL';
export const STAFF_REGISTER_RESET = 'STAFF_REGISTER_RESET';
