export const TOPUP_CREATE_REQUEST = 'TOPUP_CREATE_REQUEST';
export const TOPUP_CREATE_SUCCESS = 'TOPUP_CREATE_SUCCESS';
export const TOPUP_CREATE_FAIL = 'TOPUP_CREATE_FAIL';
export const TOPUP_CREATE_RESET = 'TOPUP_CREATE_RESET';

export const TOPUP_DETAILS_REQUEST = 'TOPUP_DETAILS_REQUEST';
export const TOPUP_DETAILS_SUCCESS = 'TOPUP_DETAILS_SUCCESS';
export const TOPUP_DETAILS_FAIL = 'TOPUP_DETAILS_FAIL';

export const TOPUP_CONFIRM_REQUEST = 'TOPUP_CONFIRM_REQUEST';
export const TOPUP_CONFIRM_SUCCESS = 'TOPUP_CONFIRM_SUCCESS';
export const TOPUP_CONFIRM_FAIL = 'TOPUP_CONFIRM_FAIL';
export const TOPUP_CONFIRM_RESET = 'TOPUP_CONFIRM_RESET';

export const TOPUP_LIST_REQUEST = 'TOPUP_LIST_REQUEST';
export const TOPUP_LIST_SUCCESS = 'TOPUP_LIST_SUCCESS';
export const TOPUP_LIST_FAIL = 'TOPUP_LIST_FAIL';
