export const VERIFY_CREATE_REQUEST = 'VERIFY_CREATE_REQUEST';
export const VERIFY_CREATE_SUCCESS = 'VERIFY_CREATE_SUCCESS';
export const VERIFY_CREATE_FAIL = 'VERIFY_CREATE_FAIL';
export const VERIFY_CREATE_RESET = 'VERIFY_CREATE_RESET';
